apiVersion: v1
kind: Service
metadata:
  name: linkroom
  namespace: linkroom
  labels:
    app.kubernetes.io/name: linkroom
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: linkroom
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
